    // StringMap mMenu  = CreateTrie();
    // KeyValues kPanel = new KeyValues("menu");

    // GetNativeString(1, sCommandBase, sizeof(sCommandBase));
    // GetNativeString(2, sTitle, sizeof(sTitle));
    // GetNativeString(3, sMessage, sizeof(sMessage));

    // kPanel.SetString("title", sTitle);
    // kPanel.SetString("msg", sMessage);
    // kPanel.SetString("command", sCommandBase);
    // kPanel.SetNum("level", 1);

    // mMenu.SetValue("count", 1);
    // mMenu.SetValue("type", iType);
    // mMenu.SetValue("1", kPanel);
	
	